feat: add ability to disable error stacktrace logging and daily sets that are unavailable in some markets
Prem-ium/BingRewards pull request #79
Opened 2023-04-19 15:30 UTC by meghrathod

By default stacktrace is printed for all users which can be annoying and difficult to debug any issues for normal users. Adding a flag to enable or disable stacktrace through environment variable will be highly appreciated. Instead I've added print statements whenever exceptions occur with proper details about the exception.

Apart from that in India and many other markets, where I come from there is no daily sets and which results in error about the buttons not found so made it an optional flag with default value true.

Let me know your feedback on the commits or merge them if they seem appropriate.

2023-04-19 16:44 UTC, meghrathod commented on main.py
> +        sleep(100)
500 seconds for restarting was looking too long for actual restart as well as for diagonosis of problems

2023-04-19 19:15 UTC, Prem-ium commented on main.py
> +        sleep(100)
500 seconds is there for manual intervention from the user. The rest of your pull request looks good, change the sleep time back a& I'll merge.

2023-04-19 19:16 UTC, Prem-ium requested changes
Change Sleep Time in case of failure back to original amount.

Otherwise, great work.

2023-04-21 06:43 UTC, meghrathod commented
Done. Kindly merge, I still feel a shorter restart time is good for unattended execution when deployed on cloud for example. Maybe we can add a flag for this as well.

2023-04-21 06:50 UTC, Prem-ium commented
Instead of using LOGGING, we can rename your new env to DEBUGGING which, if enabled, prints the traceback and pauses for a longer period of time allowing enough time of debugging on execution. If not enabled, we can have the script close the driver earlier as you suggested.

2023-04-21 06:52 UTC, Prem-ium approved these changes
Ready to merge. Good work.

2023-04-21 06:53 UTC, merged